// Example code generated by ChatGPT:

// MapDashboard.jsx
import React, { useEffect, useState } from "react";
import { MapContainer, TileLayer, GeoJSON, Popup } from "react-leaflet";

const geojsonData = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": { "name": "Area A", "value": 10 },
      "geometry": {
        "type": "Polygon",
        "coordinates": [[[-1.5, 54.9], [-1.4, 54.9], [-1.4, 55.0], [-1.5, 55.0], [-1.5, 54.9]]]
      }
    },
    {
      "type": "Feature",
      "properties": { "name": "Area B", "value": 30 },
      "geometry": {
        "type": "Polygon",
        "coordinates": [[[-1.6, 54.9], [-1.5, 54.9], [-1.5, 55.0], [-1.6, 55.0], [-1.6, 54.9]]]
      }
    }
  ]
};

const MapDashboard = () => {
  const [selectedArea, setSelectedArea] = useState(null);

  const styleFeature = (feature) => ({
    fillColor: feature.properties.value > 20 ? "#e41a1c" : "#377eb8",
    weight: 1,
    color: "white",
    fillOpacity: 0.7,
  });

  const onEachFeature = (feature, layer) => {
    layer.on({
      click: () => {
        setSelectedArea(feature.properties);
      },
    });
  };

  // Load GeoJSON data from public folder (or API)
  useEffect(() => {
    fetch("/data/secondaries_for_dashboard.geojson")
      .then((res) => {
        if (!res.ok) throw new Error("Failed to fetch GeoJSON");
        return res.json();
      })
      .then((data) => setGeoData(data))
      .catch((err) => console.error(err));
  }, []);


  return (
    <div className="flex">
      {/* Map Section */}
      <div className="w-3/4 h-screen">
        <MapContainer center={[54.95, -1.5]} zoom={10} style={{ height: "100%", width: "100%" }}>
          <TileLayer
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            attribution="&copy; OpenStreetMap contributors"
          />
          <GeoJSON data={geojsonData} style={styleFeature} onEachFeature={onEachFeature}>
            <Popup>
              <b>{selectedArea?.name}</b><br />
              Value: {selectedArea?.value}
            </Popup>
          </GeoJSON>
        </MapContainer>
      </div>

      {/* Side Panel Section */}
      <div className="w-1/4 p-4 bg-gray-50 border-l">
        {selectedArea ? (
          <div>
            <h2 className="text-lg font-semibold">{selectedArea.name}</h2>
            <p>Value: {selectedArea.value}</p>
          </div>
        ) : (
          <p>Click an area to see details</p>
        )}
      </div>
    </div>
  );
};

export default MapDashboard;
